# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 05:13
from __future__ import unicode_literals

import companies.models
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=companies.models.image_upload_to_company_folder),
        ),
    ]
