# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_dealoftheday_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealoftheday',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image_field', '120x100', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='dealoftheday',
            name='cropping_free',
            field=image_cropping.fields.ImageRatioField('image_field', '300x230', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping free'),
        ),
        migrations.AlterField(
            model_name='dealoftheday',
            name='image',
            field=models.ImageField(upload_to='images/dotd/'),
        ),
    ]
