# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20170318_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealoftheday',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dealoftheday',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealoftheday',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
