# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='style',
            field=models.CharField(blank=True, choices=[('rate', 'Rating'), ('text', 'Text Response')], max_length=25, null=True),
        ),
    ]
