# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='rewards',
            new_name='reward',
        ),
    ]
